### ISSUE TITLE
Centos 7: Error "Device eth1 does not seem to be present" with private network

### ISSUE THREAD

**Issue by jong99** [jedi4ever/veewee#970]
Trying to use a private network with the new Centos 7 config doesn't work and results in the error below:

Steps to reproduce:

```
veewee vbox define 'centos70' CentOS-7.0-1406-x86_64-netinstall --force
veewee vbox build 'centos70' 
veewee vbox export 'centos70'
vagrant box add 'centos70' centos70.box
vagrant init 'centos70'
```

Now edit the Vagrantfile and uncomment the line:

```
  config.vm.network "private_network", ip: "192.168.33.10"
```

Then run:

```
vagrant up
```

This results in the following error:

```
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ARPCHECK=no /sbin/ifup eth1 2> /dev/null

Stdout from the command:

ERROR    : [/etc/sysconfig/network-scripts/ifup-eth] Device eth1 does not seem to be present, delaying initialization.


Stderr from the command:
```

**Comment by klub** [comment]
Removing /etc/udev/rules.d/70-persistent-net.rules
seems to have worked for me too.

**Comment by monomidev** [comment]
@mpapis sorry for the delay, I think it is a combination of bad base box configuration (causing the extra ifcfg file) and the rules file.  I will see what I can put together.

**Comment by dankeder** [comment]
I have vagrant 1.7.2 and I am encoutering this issue too.

As far as I can tell, the problem is that Vagrant expects the second network interface to be called `eth1`, and it wants to create configuration for it in `/etc/sysconfig/network-scripts/ifcfg-eth1`. But network interfaces have a different naming convention in Centos 7 (and Fedora as well) - the network interface in question is actually called like `enp0s8` (or something similar - you can get the real interface name by running `ip link` in the VM shell).

The solution would be to explicitly specify the interface name in Vagrantfile - which I don't know how to do, but maybe somebody else does.

A possible workaround which I used is to disable interface renaming by adding `net.ifnames=0` to `/etc/sysconfig/grub` in the base VM image.

**Comment by mpapis** [comment]
I think `net.ifnames=0` is the best option, we actually want the old behavior for virtual machines, the new names are only trouble in our use case - btw. I think I used the same thing for `openSUSE`

**Comment by Stono** [comment]
So I have this issue (I think) with RHEL7.  
I have created an image using net.ifnames=0 etc so my interfaces are named correctly, however when I add a private network using Vagrant I get:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 

Stdout from the command:



usage: ifdown <device name>
```

When i log onto a box there is a random file....
```
/etc/sysconfig/network-scripts/ifcfg-
```

Karl

**Comment by mpapis** [comment]
You will have to debug this process yourself, I'm stepping down to only advise on fixing the issues (see: <http://niczsoft.com/2015/02/changes-in-my-open-source-life/>)

**Comment by pebreo** [comment]
I was able to fix this issue by upgrading to Vagrant v1.7.2.

**Comment by pgporada** [comment]
This still happens to me on Vagrant v1.7.2

**Comment by PrinceP3** [comment]
the problem happens on Vagrant v1.7.2 !!!

**Comment by DanielAron** [comment]
Same problem here following this tutorial:
https://github.com/openMF/mifosx/wiki/MifosX-Vagrant-Box-Setup
Vagrant v1.7.2
